### ISSUE TITLE
Trouble with modules in "Blueprint to Constant Combinator"

### ISSUE THREAD

**Issue by evgenyzaikin** [JensForstmann/gaming-tools#1]
Once migrated to the new site, modules are no longer added to the output blueprints. The problem is reproduced with the default settings, but I do not use "include requester chest" and change the maximum signals per constant combinator to 20.

**Comment by JensForstmann** [comment]
Hey,

this is fixed with 7700b43eca3797448bf3ef42debc41464be33468
